
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/information_center?characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8088
  auth: false
  servlet:
    context-path: /api

token:
  salt: this
  expired-time: "#{1000*60*60*1}" #millisSeconde
  rememberme-time: "#{1000*60*60*7}"

mybatis:
  mapper-locations: classpath:mybatis/mapperxml/*.xml



pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: info
    com.hnu.softwarecollege.infocenter: debug

